server:
  port: 56085
  servlet:
    context-path: /sailing

spring:
  application:
    name: sailing

  main:
    allow-bean-definition-overriding: true



  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8

  redis:
    host: localhost
    port: 6379
    shutdown-timeout: 100
    lettuce:
      pool:
        max-idle: 8
        min-idle: 0
        max-active: 8
        max-wait: 10000
    timeout: 10000
#    password: 111111

sms:
  qcloud:
    appId: 1400562275
    appKey: c46253a12bf5402cc311bcc916eca4f3
    templateId: 1084544
    sign: 你二大爷

swagger:
  enable: true

logging:
  config: classpath:log4j2.xml
    


